<a href="https://colab.research.google.com/github/saransh437/Python_practice/blob/main/Advance_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Introduction to numpy:
# this is an open-source library of python and this is used for the
# scientific calculations.
# list is hetrogeneous data type and numpy is homogeneuos data type

In [ ]:
a= [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
import numpy as np
a = np.array([1,2,3])
a*3

array([3, 6, 9])

In [ ]:
a=[1,2,3]
b=np.array(a)
b

array([1, 2, 3])

In [ ]:
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>

In [ ]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print('total shape',b.shape)   ###  shape = row,column
print('Total Element',b.size)  ###  size = row*column
print('Total Dimension',b.ndim) ### total dimension = 2

total shape (3, 3)
Total Element 9
Total Dimension 2

In [ ]:
# pre-built functions of Numpy
# (1). Zeros()-> it will create an array in which all the values will be 0
# in either one dimensional or multi-dimensional.
a= np.zeros(3)
a
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# (2). ones()-> it will create an array in which all the values will be 1
# in either one dimensional or multi-dimensional.
a= np.ones(3)
print(a)
b = np.ones((3,4))    # two element cant go in one dimension
print(b)
print(b.dtype)

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64

In [ ]:
b = np.ones((5,6))
print(b.size)
print(b.shape)
print(b.ndim)

30
(5, 6)
2

In [ ]:
np.arange(0,10,2)  # range

array([0, 2, 4, 6, 8])

In [ ]:
arr = np.array([[1],[4]])
print(arr.dtype)     # used to get the data type of the element present in the arr
print(arr.itemsize)

int64
8

In [ ]:
# 3). eye(): it will create an array in which diagonal position elements are 1
#            and rest all are 0.

In [ ]:
a= np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# 4). diag(): use to set our custom values on diagonal position
a = np.array([1,2,3,4])
b=np.diag(a)
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
# 5). Random Module
# a). Randint() ---> it will create random numbers in a given range.
# syntax: np.random.randint(min,max,total)

In [ ]:
a= np.random.randint(1,10,3)
a

array([2, 8, 3])

In [ ]:
# b). rand -> it will create random numbers in range 0-1.
a= np.random.rand(2)
a

array([0.88916582, 0.79595669])

In [ ]:
# c). seed --> it will fix our random generated data.
np.random.seed(3)
a=np.random.randint(1,10,3)
a

array([9, 4, 9])

In [ ]:
#  View vs Copy
# View means modification in orignal data and copy means chnages in duplicare data
#  will not reflect the orignal data

In [ ]:
a = np.array([1,2,3,4])
b = a.view()

b[0] = 100

print(a)   # original array
print(b)   # view array

[100   2   3   4]
[100   2   3   4]

In [ ]:
a = np.array([1,2,3,4])
b = a.copy()

b[0] = 100

print(a)
print(b)

[1 2 3 4]
[100   2   3   4]

In [ ]:
# operations on Array
# 1. Arange(): it will work as foor loop in numpy
a=np.arange(1,12)
a
b= a>10
a[b]

array([11])

In [ ]:
# reshanping
# n(rows) * n(columns) = n(total_numbers)

a=np.random.randint(1,20,12)
a.reshape(2,6)

array([[ 3,  3,  2,  6,  9, 15],
       [ 2, 11,  8, 12,  2, 16]])

In [ ]:
a=np.arange(1,5).reshape(2,2)
print(a)
b=np.arange(5,9).reshape(2,2)
print(b)
a+b

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

array([[ 6,  8],
       [10, 12]])

In [ ]:
a*b

array([[ 5, 12],
       [21, 32]])

In [ ]:
a.dot(b)    # matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
a= np.arange(1,5)
a**2

array([ 1,  4,  9, 16])

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
# LinSpace() ---> it will return same gap values in a given range.

In [ ]:
a=np.linspace(0,9,10)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Unique() --> it will return # arrays.
# arr---> return orignal values of array.
# return_index = True --> return index value of unique numbers.
#  return_counts = True --> it Will return total frequency of each unique Value.

In [ ]:
a= np.array([1,2,3,2,2,2,3,3,2,4,5])
a

array([1, 2, 3, 2, 2, 2, 3, 3, 2, 4, 5])

In [ ]:
np.unique(a , return_index = True, return_counts=True)

(array([1, 2, 3, 4, 5]), array([ 0,  1,  2,  9, 10]), array([1, 5, 3, 1, 1]))

In [ ]:
# hstack and vstack()
a=np.arange(1,5).reshape(2,2)
b=np.arange(5,9).reshape(2,2)

np.hstack((a,b))
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.random.seed(3)
a =np.random.randint(30,80,36).reshape(2,18)
b =np.random.randint(30,80,36).reshape(4,9)
c =np.random.randint(30,80,36).reshape(6,6)
print(a)
print(b)
print(c)

[[72 54 33 38 30 51 49 40 73 71 40 51 68 62 50 74 59 69]
 [44 56 47 56 52 32 32 31 56 35 70 76 63 59 72 54 37 73]]
[[63 45 78 67 50 60 79 51 44]
 [58 30 30 71 48 67 37 67 76]
 [63 79 31 51 40 73 66 65 57]
 [46 46 62 46 48 41 62 61 43]]
[[67 60 78 63 79 32]
 [58 66 56 70 74 78]
 [40 78 66 57 79 51]
 [79 70 69 59 62 78]
 [39 63 77 54 41 50]
 [40 78 46 42 34 74]]

In [ ]:
a =np.arange(6,10).reshape(2,2)
b =np.arange(11,15).reshape(2,2)
np.hstack((a,b))

array([[ 6,  7, 11, 12],
       [ 8,  9, 13, 14]])

In [ ]:
##################################################### PANDAS######################################################################

In [1]:
# pandas : pandas is an open source library which is used for handling data manipulation
import pandas as pd

In [2]:
# data structure in pandas:::::
# 1. series: it store only values not column name and it is one dimensional
# 2. Dataframe: It store values with column name and it is multi dimnesional

In [3]:
a = pd.Series([1,2,3,4])
a

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
type(a)

pandas.core.series.Series

In [5]:
### DataFrame

a = {
    'emp_id':[1,2,3,4],
    'Emp_name':['sara' , 'tanish' , 'rahul','mihir']
}

In [6]:
df = pd.DataFrame(a)
df

   emp_id Emp_name
0       1     sara
1       2   tanish
2       3    rahul
3       4    mihir

In [7]:
# to export the data
df.to_csv('EMP.csv')
# to export the data into excel
# df.to_excel

In [8]:
# to import the data in csv
df = pd.read_csv('/content/EMP.csv')

In [16]:
# ---------------------------------------- PANDAS_TASK------------------------------------------------------------------

In [13]:
st = {
    'st_id': [1,2,3,4,5,6,7,8,9,10],
    'st_name':['sara','puspha','rahul','mihir','manish','mohit','aaryan','Ayush','tushar','Vinay'],
    'st_course':['data science', 'data science','data science','MERN','JAVA','data science','DIGITAL_MARKETING','data science','C','DATA_ENG'],
    'Duration':[10,10,8,10,8,10,9,8,1,8],
    'fee':[55000,45000,60000,50000,30000,52500,65000,45000,35000,63000]
}

In [14]:
df = pd.DataFrame(st)
df

   st_id st_name          st_course  Duration    fee
0      1    sara       data science        10  55000
1      2  puspha       data science        10  45000
2      3   rahul       data science         8  60000
3      4   mihir               MERN        10  50000
4      5  manish               JAVA         8  30000
5      6   mohit       data science        10  52500
6      7  aaryan  DIGITAL_MARKETING         9  65000
7      8   Ayush       data science         8  45000
8      9  tushar                  C         1  35000
9     10   Vinay           DATA_ENG         8  63000

In [15]:
df.head()

   st_id st_name     st_course  Duration    fee
0      1    sara  data science        10  55000
1      2  puspha  data science        10  45000
2      3   rahul  data science         8  60000
3      4   mihir          MERN        10  50000
4      5  manish          JAVA         8  30000

In [16]:
df.to_csv('STUDENT_DATA.csv')